#!/usr/bin/env python
import optparse

import adapter_factory
from SWDProtocol import *


optparser = optparse.OptionParser(usage='%prog [options]')
adapter_factory.add_options(optparser)
(options, args) = optparser.parse_args()

adapter = adapter_factory.load(optparser, options)

def readIDCODE(adapter):
    return adapter.readSWD(0xa5)

#print hex(readIDCODE(adapter))

import DebugPort
dap = DebugPort.DebugPort(adapter)
print hex(dap.idcode())
